### 1. Import libraries and load dataset

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("winequality-red.csv")

df.head(10)
df.tail(10)

df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1596 non-null   float64
 1   volatile acidity      1596 non-null   float64
 2   citric acid           1596 non-null   float64
 3   residual sugar        1596 non-null   float64
 4   chlorides             1596 non-null   float64
 5   free sulfur dioxide   1596 non-null   float64
 6   total sulfur dioxide  1596 non-null   float64
 7   density               1596 non-null   float64
 8   pH                    1596 non-null   float64
 9   sulphates             1596 non-null   float64
 10  alcohol               1596 non-null   float64
 11  quality               1596 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 149.8 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000
mean,8.314160,0.527954,0.270276,2.535558,0.087120,15.858396,46.382206,0.996744,3.311917,0.656385,10.421147,5.637218
std,1.732203,0.179176,0.193894,1.405515,0.045251,10.460554,32.839138,0.001888,0.153346,0.163057,1.060371,0.807080
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.860000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996745,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997833,3.400000,0.730000,11.100000,6.000000
max,15.600000,1.580000,0.790000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,1.980000,14.000000,8.000000

### 2. Find-S Algorithm

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

def find_s(X, y):
    hypo = None
    print("Initial Hypothesis:", hypo)

    for i in range(len(X)):
        if y[i] == "acceptable":
            if hypo is None:
                hypo = X[i].copy()
            else:
                for j in range(len(hypo)):
                    if hypo[j] != X[i][j]:
                        hypo[j] = '?'

        print(f"After Training Example {i+1}")
        print(hypo)

    return hypo

final_hypo = find_s(X, y)
print("\nFinal Hypothesis")
print(final_hypo)

Initial Hypothesis: None
After Training Example 1
None
After Training Example 2
None
After Training Example 3
None
After Training Example 4
None
After Training Example 5
None
After Training Example 6
None
After Training Example 7
None
After Training Example 8
None
After Training Example 9
None
After Training Example 10
None
After Training Example 11
None
After Training Example 12
None
After Training Example 13
None
After Training Example 14
None
After Training Example 15
None
After Training Example 16
None
After Training Example 17
None
After Training Example 18
None
After Training Example 19
None
After Training Example 20
None
After Training Example 21
None
After Training Example 22
None
After Training Example 23
None
After Training Example 24
None
After Training Example 25
None
After Training Example 26
None
After Training Example 27
None
After Training Example 28
None
After Training Example 29
None
After Training Example 30
None
After Training Example 31
None
After Training Example 32
None
After Training Example 33
None
After Training Example 34
None
After Training Example 35
None
After Training Example 36
None
After Training Example 37
None
After Training Example 38
None
After Training Example 39
None
After Training Example 40
None
After Training Example 41
None
After Training Example 42
None
After Training Example 43
None
After Training Example 44
None
After Training Example 45
None
After Training Example 46
None
After Training Example 47
None
After Training Example 48
None
After Training Example 49
None
After Training Example 50
None
After Training Example 51
None
After Training Example 52
None
After Training Example 53
None
After Training Example 54
None
After Training Example 55
None
After Training Example 56
None
After Training Example 57
None
After Training Example 58
None
After Training Example 59
None
After Training Example 60
None
After Training Example 61
None
After Training Example 62
None
After Training Example 63
None
After Training Example 64
None
After Training Example 65
None
After Training Example 66
None
After Training Example 67
None
After Training Example 68
None
After Training Example 69
None
After Training Example 70
None
After Training Example 71
None
After Training Example 72
None
After Training Example 73
None
After Training Example 74
None
After Training Example 75
None
After Training Example 76
None
After Training Example 77
None
After Training Example 78
None
After Training Example 79
None
After Training Example 80
None
After Training Example 81
None
After Training Example 82
None
After Training Example 83
None
After Training Example 84
None
After Training Example 85
None
After Training Example 86
None
After Training Example 87
None
After Training Example 88
None
After Training Example 89
None
After Training Example 90
None
After Training Example 91
None
After Training Example 92
None
After Training Example 93
None
After Training Example 94
None
After Training Example 95
None
After Training Example 96
None
After Training Example 97
None
After Training Example 98
None
After Training Example 99
None
After Training Example 100
None
After Training Example 101
None
After Training Example 102
None
After Training Example 103
None
After Training Example 104
None
After Training Example 105
None
After Training Example 106
None
After Training Example 107
None
After Training Example 108
None
After Training Example 109
None
After Training Example 110
None
After Training Example 111
None
After Training Example 112
None
After Training Example 113
None
After Training Example 114
None
After Training Example 115
None
After Training Example 116
None
After Training Example 117
None
After Training Example 118
None
After Training Example 119
None
After Training Example 120
None
After Training Example 121
None
After Training Example 122
None
After Training Example 123
None
After Training Example 124
None
After Training Example 125
None
After Training Example 126
None
After Training Example 127
None
After Training Example 128
None
After Training Example 129
None
After Training Example 130
None
After Training Example 131
None
After Training Example 132
None
After Training Example 133
None
After Training Example 134
None
After Training Example 135
None
After Training Example 136
None
After Training Example 137
None
After Training Example 138
None
After Training Example 139
None
After Training Example 140
None
After Training Example 141
None
After Training Example 142
None
After Training Example 143
None
After Training Example 144
None
After Training Example 145
None
After Training Example 146
None
After Training Example 147
None
After Training Example 148
None
After Training Example 149
None
After Training Example 150
None
After Training Example 151
None
After Training Example 152
None
After Training Example 153
None
After Training Example 154
None
After Training Example 155
None
After Training Example 156
None
After Training Example 157
None
After Training Example 158
None
After Training Example 159
None
After Training Example 160
None
After Training Example 161
None
After Training Example 162
None
After Training Example 163
None
After Training Example 164
None
After Training Example 165
None
After Training Example 166
None
After Training Example 167
None
After Training Example 168
None
After Training Example 169
None
After Training Example 170
None
After Training Example 171
None
After Training Example 172
None
After Training Example 173
None
After Training Example 174
None
After Training Example 175
None
After Training Example 176
None
After Training Example 177
None
After Training Example 178
None
After Training Example 179
None
After Training Example 180
None
After Training Example 181
None
After Training Example 182
None
After Training Example 183
None
After Training Example 184
None
After Training Example 185
None
After Training Example 186
None
After Training Example 187
None
After Training Example 188
None
After Training Example 189
None
After Training Example 190
None
After Training Example 191
None
After Training Example 192
None
After Training Example 193
None
After Training Example 194
None
After Training Example 195
None
After Training Example 196
None
After Training Example 197
None
After Training Example 198
None
After Training Example 199
None
After Training Example 200
None
After Training Example 201
None
After Training Example 202
None
After Training Example 203
None
After Training Example 204
None
After Training Example 205
None
After Training Example 206
None
After Training Example 207
None
After Training Example 208
None
After Training Example 209
None
After Training Example 210
None
After Training Example 211
None
After Training Example 212
None
After Training Example 213
None
After Training Example 214
None
After Training Example 215
None
After Training Example 216
None
After Training Example 217
None
After Training Example 218
None
After Training Example 219
None
After Training Example 220
None
After Training Example 221
None
After Training Example 222
None
After Training Example 223
None
After Training Example 224
None
After Training Example 225
None
After Training Example 226
None
After Training Example 227
None
After Training Example 228
None
After Training Example 229
None
After Training Example 230
None
After Training Example 231
None
After Training Example 232
None
After Training Example 233
None
After Training Example 234
None
After Training Example 235
None
After Training Example 236
None
After Training Example 237
None
After Training Example 238
None
After Training Example 239
None
After Training Example 240
None
After Training Example 241
None
After Training Example 242
None
After Training Example 243
None
After Training Example 244
None
After Training Example 245
None
After Training Example 246
None
After Training Example 247
None
After Training Example 248
None
After Training Example 249
None
After Training Example 250
None
After Training Example 251
None
After Training Example 252
None
After Training Example 253
None
After Training Example 254
None
After Training Example 255
None
After Training Example 256
None
After Training Example 257
None
After Training Example 258
None
After Training Example 259
None
After Training Example 260
None
After Training Example 261
None
After Training Example 262
None
After Training Example 263
None
After Training Example 264
None
After Training Example 265
None
After Training Example 266
None
After Training Example 267
None
After Training Example 268
None
After Training Example 269
None
After Training Example 270
None
After Training Example 271
None
After Training Example 272
None
After Training Example 273
None
After Training Example 274
None
After Training Example 275
None
After Training Example 276
None
After Training Example 277
None
After Training Example 278
None
After Training Example 279
None
After Training Example 280
None
After Training Example 281
None
After Training Example 282
None
After Training Example 283
None
After Training Example 284
None
After Training Example 285
None
After Training Example 286
None
After Training Example 287
None
After Training Example 288
None
After Training Example 289
None
After Training Example 290
None
After Training Example 291
None
After Training Example 292
None
After Training Example 293
None
After Training Example 294
None
After Training Example 295
None
After Training Example 296
None
After Training Example 297
None
After Training Example 298
None
After Training Example 299
None
After Training Example 300
None
After Training Example 301
None
After Training Example 302
None
After Training Example 303
None
After Training Example 304
None
After Training Example 305
None
After Training Example 306
None
After Training Example 307
None
After Training Example 308
None
After Training Example 309
None
After Training Example 310
None
After Training Example 311
None
After Training Example 312
None
After Training Example 313
None
After Training Example 314
None
After Training Example 315
None
After Training Example 316
None
After Training Example 317
None
After Training Example 318
None
After Training Example 319
None
After Training Example 320
None
After Training Example 321
None
After Training Example 322
None
After Training Example 323
None
After Training Example 324
None
After Training Example 325
None
After Training Example 326
None
After Training Example 327
None
After Training Example 328
None
After Training Example 329
None
After Training Example 330
None
After Training Example 331
None
After Training Example 332
None
After Training Example 333
None
After Training Example 334
None
After Training Example 335
None
After Training Example 336
None
After Training Example 337
None
After Training Example 338
None
After Training Example 339
None
After Training Example 340
None
After Training Example 341
None
After Training Example 342
None
After Training Example 343
None
After Training Example 344
None
After Training Example 345
None
After Training Example 346
None
After Training Example 347
None
After Training Example 348
None
After Training Example 349
None
After Training Example 350
None
After Training Example 351
None
After Training Example 352
None
After Training Example 353
None
After Training Example 354
None
After Training Example 355
None
After Training Example 356
None
After Training Example 357
None
After Training Example 358
None
After Training Example 359
None
After Training Example 360
None
After Training Example 361
None
After Training Example 362
None
After Training Example 363
None
After Training Example 364
None
After Training Example 365
None
After Training Example 366
None
After Training Example 367
None
After Training Example 368
None
After Training Example 369
None
After Training Example 370
None
After Training Example 371
None
After Training Example 372
None
After Training Example 373
None
After Training Example 374
None
After Training Example 375
None
After Training Example 376
None
After Training Example 377
None
After Training Example 378
None
After Training Example 379
None
After Training Example 380
None
After Training Example 381
None
After Training Example 382
None
After Training Example 383
None
After Training Example 384
None
After Training Example 385
None
After Training Example 386
None
After Training Example 387
None
After Training Example 388
None
After Training Example 389
None
After Training Example 390
None
After Training Example 391
None
After Training Example 392
None
After Training Example 393
None
After Training Example 394
None
After Training Example 395
None
After Training Example 396
None
After Training Example 397
None
After Training Example 398
None
After Training Example 399
None
After Training Example 400
None
After Training Example 401
None
After Training Example 402
None
After Training Example 403
None
After Training Example 404
None
After Training Example 405
None
After Training Example 406
None
After Training Example 407
None
After Training Example 408
None
After Training Example 409
None
After Training Example 410
None
After Training Example 411
None
After Training Example 412
None
After Training Example 413
None
After Training Example 414
None
After Training Example 415
None
After Training Example 416
None
After Training Example 417
None
After Training Example 418
None
After Training Example 419
None
After Training Example 420
None
After Training Example 421
None
After Training Example 422
None
After Training Example 423
None
After Training Example 424
None
After Training Example 425
None
After Training Example 426
None
After Training Example 427
None
After Training Example 428
None
After Training Example 429
None
After Training Example 430
None
After Training Example 431
None
After Training Example 432
None
After Training Example 433
None
After Training Example 434
None
After Training Example 435
None
After Training Example 436
None
After Training Example 437
None
After Training Example 438
None
After Training Example 439
None
After Training Example 440
None
After Training Example 441
None
After Training Example 442
None
After Training Example 443
None
After Training Example 444
None
After Training Example 445
None
After Training Example 446
None
After Training Example 447
None
After Training Example 448
None
After Training Example 449
None
After Training Example 450
None
After Training Example 451
None
After Training Example 452
None
After Training Example 453
None
After Training Example 454
None
After Training Example 455
None
After Training Example 456
None
After Training Example 457
None
After Training Example 458
None
After Training Example 459
None
After Training Example 460
None
After Training Example 461
None
After Training Example 462
None
After Training Example 463
None
After Training Example 464
None
After Training Example 465
None
After Training Example 466
None
After Training Example 467
None
After Training Example 468
None
After Training Example 469
None
After Training Example 470
None
After Training Example 471
None
After Training Example 472
None
After Training Example 473
None
After Training Example 474
None
After Training Example 475
None
After Training Example 476
None
After Training Example 477
None
After Training Example 478
None
After Training Example 479
None
After Training Example 480
None
After Training Example 481
None
After Training Example 482
None
After Training Example 483
None
After Training Example 484
None
After Training Example 485
None
After Training Example 486
None
After Training Example 487
None
After Training Example 488
None
After Training Example 489
None
After Training Example 490
None
After Training Example 491
None
After Training Example 492
None
After Training Example 493
None
After Training Example 494
None
After Training Example 495
None
After Training Example 496
None
After Training Example 497
None
After Training Example 498
None
After Training Example 499
None
After Training Example 500
None
After Training Example 501
None
After Training Example 502
None
After Training Example 503
None
After Training Example 504
None
After Training Example 505
None
After Training Example 506
None
After Training Example 507
None
After Training Example 508
None
After Training Example 509
None
After Training Example 510
None
After Training Example 511
None
After Training Example 512
None
After Training Example 513
None
After Training Example 514
None
After Training Example 515
None
After Training Example 516
None
After Training Example 517
None
After Training Example 518
None
After Training Example 519
None
After Training Example 520
None
After Training Example 521
None
After Training Example 522
None
After Training Example 523
None
After Training Example 524
None
After Training Example 525
None
After Training Example 526
None
After Training Example 527
None
After Training Example 528
None
After Training Example 529
None
After Training Example 530
None
After Training Example 531
None
After Training Example 532
None
After Training Example 533
None
After Training Example 534
None
After Training Example 535
None
After Training Example 536
None
After Training Example 537
None
After Training Example 538
None
After Training Example 539
None
After Training Example 540
None
After Training Example 541
None
After Training Example 542
None
After Training Example 543
None
After Training Example 544
None
After Training Example 545
None
After Training Example 546
None
After Training Example 547
None
After Training Example 548
None
After Training Example 549
None
After Training Example 550
None
After Training Example 551
None
After Training Example 552
None
After Training Example 553
None
After Training Example 554
None
After Training Example 555
None
After Training Example 556
None
After Training Example 557
None
After Training Example 558
None
After Training Example 559
None
After Training Example 560
None
After Training Example 561
None
After Training Example 562
None
After Training Example 563
None
After Training Example 564
None
After Training Example 565
None
After Training Example 566
None
After Training Example 567
None
After Training Example 568
None
After Training Example 569
None
After Training Example 570
None
After Training Example 571
None
After Training Example 572
None
After Training Example 573
None
After Training Example 574
None
After Training Example 575
None
After Training Example 576
None
After Training Example 577
None
After Training Example 578
None
After Training Example 579
None
After Training Example 580
None
After Training Example 581
None
After Training Example 582
None
After Training Example 583
None
After Training Example 584
None
After Training Example 585
None
After Training Example 586
None
After Training Example 587
None
After Training Example 588
None
After Training Example 589
None
After Training Example 590
None
After Training Example 591
None
After Training Example 592
None
After Training Example 593
None
After Training Example 594
None
After Training Example 595
None
After Training Example 596
None
After Training Example 597
None
After Training Example 598
None
After Training Example 599
None
After Training Example 600
None
After Training Example 601
None
After Training Example 602
None
After Training Example 603
None
After Training Example 604
None
After Training Example 605
None
After Training Example 606
None
After Training Example 607
None
After Training Example 608
None
After Training Example 609
None
After Training Example 610
None
After Training Example 611
None
After Training Example 612
None
After Training Example 613
None
After Training Example 614
None
After Training Example 615
None
After Training Example 616
None
After Training Example 617
None
After Training Example 618
None
After Training Example 619
None
After Training Example 620
None
After Training Example 621
None
After Training Example 622
None
After Training Example 623
None
After Training Example 624
None
After Training Example 625
None
After Training Example 626
None
After Training Example 627
None

### 3. Candidate Elimination Algorithm

In [9]:
import copy

def candidate_elimination(concepts, target):
    specific = [concepts[0].copy()]
    general = [["?" for _ in range(len(specific[0]))]]

    print("Initial S:", specific)
    print("Initial G:", general)

    for i, h in enumerate(concepts):
        if target[i] == "acceptable":

            for x in range(len(specific)):
                if h[x] != specific[x][x]:
                    specific[x][x] = '?'

        else:

            for x in range(len(specific)):
                if h[x] == specific[x][x]:
                    general.append(
                        ["?" if j != x else specific[x][x]
                         for j in range(len(specific))]
                    )

        print("\nExample", i + 1)
        print("S =", specific)
        print("G =", general)

    return specific, general


S, G = candidate_elimination(X, y)

print("\nFinal Specific Boundary")
print(S)

print("\nFinal General Boundary")
for g in G:
    print(g)

Streaming output truncated to the last 5000 lines.
Example 607
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 608
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 609
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 610
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 611
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 612
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 613
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 614
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 615
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 616
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 617
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 618
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 619
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 620
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 621
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 622
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 623
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 624
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 625
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 626
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 627
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 628
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 629
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 630
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 631
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 632
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 633
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 634
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 635
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 636
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 637
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 638
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 639
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 640
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 641
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 642
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 643
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 644
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 645
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 646
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 647
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 648
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 649
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])]
G = [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)], [np.float64(7.4)]]

Example 650
S = [array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,

In [11]:
df.head(10)
df.tail(10)
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1596 non-null   float64
 1   volatile acidity      1596 non-null   float64
 2   citric acid           1596 non-null   float64
 3   residual sugar        1596 non-null   float64
 4   chlorides             1596 non-null   float64
 5   free sulfur dioxide   1596 non-null   float64
 6   total sulfur dioxide  1596 non-null   float64
 7   density               1596 non-null   float64
 8   pH                    1596 non-null   float64
 9   sulphates             1596 non-null   float64
 10  alcohol               1596 non-null   float64
 11  quality               1596 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 149.8 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000,1596.000000
mean,8.314160,0.527954,0.270276,2.535558,0.087120,15.858396,46.382206,0.996744,3.311917,0.656385,10.421147,5.637218
std,1.732203,0.179176,0.193894,1.405515,0.045251,10.460554,32.839138,0.001888,0.153346,0.163057,1.060371,0.807080
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.860000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996745,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997833,3.400000,0.730000,11.100000,6.000000
max,15.600000,1.580000,0.790000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,1.980000,14.000000,8.000000